library(shiny)
library(shinyBS)

# Define UI for application
shinyUI(fluidPage(
  
  # Application title
  h2("Monthly and annual summary of SWMP parameters"),
  
  h4('Created by Marcus W. Beck,', a('beck.marcus@epa.gov', href = 'mailto:beck.marcus@epa.gov')),
  
  p('This interactive widget provides graphical summaries of water quality and weather station data from the System Wide Monitoring Program of the National Estuarine Research Reserve System ', a('(NERRS).', href = 'http://www.nerrs.noaa.gov/', target = '_blank'), 'The drop down menus can be used to select the station, date range, and parameter for plotting. The raw data used for plotting include all SWMP records from the earliest date at each station.  The data were downloaded from the', a('CDMO', href='http://cdmo.baruch.sc.edu/', target = '_blank'), 'on November 25th, 2014 and include observations up to that date.  Plots are based on daily averages for each parameter. See the', a('GitHub repository', href='https://github.com/fawda123/swmp_summary', target = '_blank'), 'for source code.'),
  
  # buttons on top
  fluidRow(
    
    column(4, 
      h3('Select station'),
  
      selectInput("stat", label = '', 
        choices = list(
          'acebbwq' = 'acebbwq',
          'acebpmet' = 'acebpmet',
          'acefcwq' = 'acefcwq',
          'acemcwq' = 'acemcwq',
          'acercwq' = 'acercwq',
          'acespwq' = 'acespwq',
          'apacpwq' = 'apacpwq',
          'apadbwq' = 'apadbwq',
          'apaebmet' = 'apaebmet',
          'apaebwq' = 'apaebwq',
          'apaeswq' = 'apaeswq',
          'cbmipwq' = 'cbmipwq',
          'cbmjbmet' = 'cbmjbmet',
          'cbmjbwq' = 'cbmjbwq',
          'cbmmcwq' = 'cbmmcwq',
          'cbmocwq' = 'cbmocwq',
          'cbmprwq' = 'cbmprwq',
          'cbmrrwq' = 'cbmrrwq',
          'cbvcbwq' = 'cbvcbwq',
          'cbvgiwq' = 'cbvgiwq',
          'cbvshwq' = 'cbvshwq',
          'cbvtcmet' = 'cbvtcmet',
          'cbvtcwq' = 'cbvtcwq',
          'delblwq' = 'delblwq',
          'deldswq' = 'deldswq',
          'delllwq' = 'delllwq',
          'delpbwq' = 'delpbwq',
          'delsjmet' = 'delsjmet',
          'delslwq' = 'delslwq',
          'elkapwq' = 'elkapwq',
          'elkcwmet' = 'elkcwmet',
          'elknmwq' = 'elknmwq',
          'elksmwq' = 'elksmwq',
          'elkvmwq' = 'elkvmwq',
          'gndbcwq' = 'gndbcwq',
          'gndbhwq' = 'gndbhwq',
          'gndblwq' = 'gndblwq',
          'gndcrmet' = 'gndcrmet',
          'gndcrwq' = 'gndcrwq',
          'gndpcwq' = 'gndpcwq',
          'grbgbmet' = 'grbgbmet',
          'grbgbwq' = 'grbgbwq',
          'grbglmet' = 'grbglmet',
          'grblrwq' = 'grblrwq',
          'grborwq' = 'grborwq',
          'grbsqwq' = 'grbsqwq',
          'gtmfmwq' = 'gtmfmwq',
          'gtmpcmet' = 'gtmpcmet',
          'gtmpcwq' = 'gtmpcwq',
          'gtmpiwq' = 'gtmpiwq',
          'gtmsswq' = 'gtmsswq',
          'hudfsmet' = 'hudfsmet',
          'hudscwq' = 'hudscwq',
          'hudskwq' = 'hudskwq',
          'hudtnwq' = 'hudtnwq',
          'hudtswq' = 'hudtswq',
          'jacb6wq' = 'jacb6wq',
          'jacb9wq' = 'jacb9wq',
          'jacbawq' = 'jacbawq',
          'jacncmet' = 'jacncmet',
          'jacnewq' = 'jacnewq',
          'job06wq' = 'job06wq',
          'job09wq' = 'job09wq',
          'job10wq' = 'job10wq',
          'job11wq' = 'job11wq',
          'job18wq' = 'job18wq',
          'job19wq' = 'job19wq',
          'job20wq' = 'job20wq',
          'jobjbmet' = 'jobjbmet',
          'kacapmet' = 'kacapmet',
          'kacbcwq' = 'kacbcwq',
          'kacdlwq' = 'kacdlwq',
          'kachdwq' = 'kachdwq',
          'kachomet' = 'kachomet',
          'kachowq' = 'kachowq',
          'kachswq' = 'kachswq',
          'kacpgwq' = 'kacpgwq',
          'kacsdwq' = 'kacsdwq',
          'kacsewq' = 'kacsewq',
          'kacsswq' = 'kacsswq',
          'lkspowq' = 'lkspowq',
          'marabwq' = 'marabwq',
          'marcemet' = 'marcemet',
          'marcewq' = 'marcewq',
          'marcwwq' = 'marcwwq',
          'marmbwq' = 'marmbwq',
          'marscwq' = 'marscwq',
          'narncwq' = 'narncwq',
          'narpcmet' = 'narpcmet',
          'narpcwq' = 'narpcwq',
          'nartbwq' = 'nartbwq',
          'nartswq' = 'nartswq',
          'nartwwq' = 'nartwwq',
          'niwcawq' = 'niwcawq',
          'niwcbwq' = 'niwcbwq',
          'niwdcwq' = 'niwdcwq',
          'niwolmet' = 'niwolmet',
          'niwolwq' = 'niwolwq',
          'niwtawq' = 'niwtawq',
          'nocecwq' = 'nocecwq',
          'noclcwq' = 'noclcwq',
          'nocrcmet' = 'nocrcmet',
          'nocrcwq' = 'nocrcwq',
          'noczbwq' = 'noczbwq',
          'owcbrwq' = 'owcbrwq',
          'owcdrwq' = 'owcdrwq',
          'owcolwq' = 'owcolwq',
          'owcowmet' = 'owcowmet',
          'owcsuwq' = 'owcsuwq',
          'owcwmwq' = 'owcwmwq',
          'pdbbpwq' = 'pdbbpwq',
          'pdbbywq' = 'pdbbywq',
          'pdbgswq' = 'pdbgswq',
          'pdbjewq' = 'pdbjewq',
          'pdbjlwq' = 'pdbjlwq',
          'pdbnnwq' = 'pdbnnwq',
          'pdbpfmet' = 'pdbpfmet',
          'rkbbmwq' = 'rkbbmwq',
          'rkbbrwq' = 'rkbbrwq',
          'rkbfbwq' = 'rkbfbwq',
          'rkbfuwq' = 'rkbfuwq',
          'rkbhcmet' = 'rkbhcmet',
          'rkblhwq' = 'rkblhwq',
          'rkbmbwq' = 'rkbmbwq',
          'rkbuhmet' = 'rkbuhmet',
          'rkbuhwq' = 'rkbuhwq',
          'sapbcwq' = 'sapbcwq',
          'sapcawq' = 'sapcawq',
          'sapdcwq' = 'sapdcwq',
          'sapfdwq' = 'sapfdwq',
          'saphdwq' = 'saphdwq',
          'sapldwq' = 'sapldwq',
          'sapmlmet' = 'sapmlmet',
          'sapmlwq' = 'sapmlwq',
          'sfbccwq' = 'sfbccwq',
          'sfbfmwq' = 'sfbfmwq',
          'sfbgcwq' = 'sfbgcwq',
          'sfbrrmet' = 'sfbrrmet',
          'sfbsmwq' = 'sfbsmwq',
          'soschwq' = 'soschwq',
          'soscmmet' = 'soscmmet',
          'sosecwq' = 'sosecwq',
          'sossewq' = 'sossewq',
          'sosvawq' = 'sosvawq',
          'soswiwq' = 'soswiwq',
          'tjrbrwq' = 'tjrbrwq',
          'tjrmmwq' = 'tjrmmwq',
          'tjroswq' = 'tjroswq',
          'tjrpewq' = 'tjrpewq',
          'tjrprwq' = 'tjrprwq',
          'tjrrcwq' = 'tjrrcwq',
          'tjrsbwq' = 'tjrsbwq',
          'tjrtlmet' = 'tjrtlmet',
          'tjrtlwq' = 'tjrtlwq',
          'weldnwq' = 'weldnwq',
          'welhtwq' = 'welhtwq',
          'welinwq' = 'welinwq',
          'wellfmet' = 'wellfmet',
          'wellmwq' = 'wellmwq',
          'welmlwq' = 'welmlwq',
          'welsmwq' = 'welsmwq',
          'welupwq' = 'welupwq',
          'wkbfrwq' = 'wkbfrwq',
          'wkbmbwq' = 'wkbmbwq',
          'wkbmrwq' = 'wkbmrwq',
          'wkbshmet' = 'wkbshmet',
          'wkbwbmet' = 'wkbwbmet',
          'wkbwbwq' = 'wkbwbwq',
          'wqbcbwq' = 'wqbcbwq',
          'wqbchmet' = 'wqbchmet',
          'wqbcrwq' = 'wqbcrwq',
          'wqbctwq' = 'wqbctwq',
          'wqbmhwq' = 'wqbmhwq',
          'wqbmpwq' = 'wqbmpwq',
          'wqbnbwq' = 'wqbnbwq',
          'wqbnswq' = 'wqbnswq',
          'wqbslwq' = 'wqbslwq'
          ),
        
        selected = "acebbwq")
      
    ),
    
    column(4,
      h3('Select date range'), 
    
      uiOutput("years")
      
    ),
  
    column(4,
      h3('Select variable'), 
    
      uiOutput("parms")
      
    )
    
  ),
  
  downloadButton('downloadplot', 'Download plot'),
  
  # Show the plot,
  plotOutput("outplot", width = "100%"),
  
  tags$style(type="text/css",
      ".shiny-output-error { visibility: hidden; }",
      ".shiny-output-error:before { visibility: hidden; }")
    
))