library(shiny)
library(shinyBS)

# Define UI for application
shinyUI(fluidPage(
  
  theme = 'styles.css',
  
  # Application title
  h2("Monthly and annual summary of SWMP parameters"),
  
  h4('Created by Marcus W. Beck,', a('beck.marcus@epa.gov', href = 'mailto:beck.marcus@epa.gov'), "Todd O'Brien,", a('todd.obrien@noaa.gov', href = 'mailto:todd.obrien@noaa.gov')),
  
  p('This interactive widget provides graphical summaries of water quality, weather, and nutrient station data from the System Wide Monitoring Program of the National Estuarine Research Reserve System ', a('(NERRS).', href = 'http://www.nerrs.noaa.gov/', target = '_blank'), 'The drop down menus can be used to select the station, date range, and parameter for plotting. The raw data used for plotting include all SWMP records from the earliest date at each station after processing to remove QAQC flags.  The data include observations through December 2014 and are current as of March 2015.  Plots are based on daily averages for each parameter.  Cumulative precipitation data are based on the daily maximum. See the', a('GitHub repository', href='https://github.com/fawda123/swmp_summary', target = '_blank'), 'for source code.'),
  
  # buttons on top
  fluidRow(
    
    column(4, 
      h3('Select station'),
  
      selectInput("stat", label = '', 
        choices = list(
          'acebbnut' = 'acebbnut',
          'acebbwq' = 'acebbwq',
          'acebpmet' = 'acebpmet',
          'acefcnut' = 'acefcnut',
          'acefcwq' = 'acefcwq',
          'acemcnut' = 'acemcnut',
          'acemcwq' = 'acemcwq',
          'acercwq' = 'acercwq',
          'acespnut' = 'acespnut',
          'acespwq' = 'acespwq',
          'apacpnut' = 'apacpnut',
          'apacpwq' = 'apacpwq',
          'apadbnut' = 'apadbnut',
          'apadbwq' = 'apadbwq',
          'apaebmet' = 'apaebmet',
          'apaebnut' = 'apaebnut',
          'apaebwq' = 'apaebwq',
          'apaegnut' = 'apaegnut',
          'apaesnut' = 'apaesnut',
          'apaeswq' = 'apaeswq',
          'apambnut' = 'apambnut',
          'apanhnut' = 'apanhnut',
          'apapcnut' = 'apapcnut',
          'aparvnut' = 'aparvnut',
          'apascnut' = 'apascnut',
          'apawpnut' = 'apawpnut',
          'cbmipnut' = 'cbmipnut',
          'cbmipwq' = 'cbmipwq',
          'cbmjbmet' = 'cbmjbmet',
          'cbmjbwq' = 'cbmjbwq',
          'cbmmcnut' = 'cbmmcnut',
          'cbmmcwq' = 'cbmmcwq',
          'cbmocnut' = 'cbmocnut',
          'cbmocwq' = 'cbmocwq',
          'cbmprwq' = 'cbmprwq',
          'cbmrrnut' = 'cbmrrnut',
          'cbmrrwq' = 'cbmrrwq',
          'cbvcbnut' = 'cbvcbnut',
          'cbvcbwq' = 'cbvcbwq',
          'cbvcinut' = 'cbvcinut',
          'cbvginut' = 'cbvginut',
          'cbvgiwq' = 'cbvgiwq',
          'cbvshnut' = 'cbvshnut',
          'cbvshwq' = 'cbvshwq',
          'cbvtcmet' = 'cbvtcmet',
          'cbvtcnut' = 'cbvtcnut',
          'cbvtcwq' = 'cbvtcwq',
          'cbvybnut' = 'cbvybnut',
          'delbbnut' = 'delbbnut',
          'delblnut' = 'delblnut',
          'delblwq' = 'delblwq',
          'deldsnut' = 'deldsnut',
          'deldswq' = 'deldswq',
          'delllnut' = 'delllnut',
          'delllwq' = 'delllwq',
          'delpbwq' = 'delpbwq',
          'delsjmet' = 'delsjmet',
          'delslnut' = 'delslnut',
          'delslwq' = 'delslwq',
          'deltbnut' = 'deltbnut',
          'elkapnut' = 'elkapnut',
          'elkapwq' = 'elkapwq',
          'elkcwmet' = 'elkcwmet',
          'elknmnut' = 'elknmnut',
          'elknmwq' = 'elknmwq',
          'elksmnut' = 'elksmnut',
          'elksmwq' = 'elksmwq',
          'elkvmnut' = 'elkvmnut',
          'elkvmwq' = 'elkvmwq',
          'gndbcnut' = 'gndbcnut',
          'gndbcwq' = 'gndbcwq',
          'gndbhnut' = 'gndbhnut',
          'gndbhwq' = 'gndbhwq',
          'gndblnut' = 'gndblnut',
          'gndblwq' = 'gndblwq',
          'gndbnnut' = 'gndbnnut',
          'gndcrmet' = 'gndcrmet',
          'gndcrnut' = 'gndcrnut',
          'gndcrwq' = 'gndcrwq',
          'gndpcnut' = 'gndpcnut',
          'gndpcwq' = 'gndpcwq',
          'grbgbmet' = 'grbgbmet',
          'grbgbnut' = 'grbgbnut',
          'grbgbwq' = 'grbgbwq',
          'grbglmet' = 'grbglmet',
          'grblrnut' = 'grblrnut',
          'grblrwq' = 'grblrwq',
          'grbornut' = 'grbornut',
          'grborwq' = 'grborwq',
          'grbsqnut' = 'grbsqnut',
          'grbsqwq' = 'grbsqwq',
          'gtmfmnut' = 'gtmfmnut',
          'gtmfmwq' = 'gtmfmwq',
          'gtmpcmet' = 'gtmpcmet',
          'gtmpcnut' = 'gtmpcnut',
          'gtmpcwq' = 'gtmpcwq',
          'gtmpinut' = 'gtmpinut',
          'gtmpiwq' = 'gtmpiwq',
          'gtmssnut' = 'gtmssnut',
          'gtmsswq' = 'gtmsswq',
          'hudfsmet' = 'hudfsmet',
          'hudscnut' = 'hudscnut',
          'hudscwq' = 'hudscwq',
          'hudsknut' = 'hudsknut',
          'hudskwq' = 'hudskwq',
          'hudtnnut' = 'hudtnnut',
          'hudtnwq' = 'hudtnwq',
          'hudtsnut' = 'hudtsnut',
          'hudtswq' = 'hudtswq',
          'jacb5nut' = 'jacb5nut',
          'jacb6nut' = 'jacb6nut',
          'jacb6wq' = 'jacb6wq',
          'jacb9nut' = 'jacb9nut',
          'jacb9wq' = 'jacb9wq',
          'jacbanut' = 'jacbanut',
          'jacbawq' = 'jacbawq',
          'jacncmet' = 'jacncmet',
          'jacnenut' = 'jacnenut',
          'jacnewq' = 'jacnewq',
          'job06wq' = 'job06wq',
          'job09nut' = 'job09nut',
          'job09wq' = 'job09wq',
          'job10nut' = 'job10nut',
          'job10wq' = 'job10wq',
          'job11wq' = 'job11wq',
          'job18wq' = 'job18wq',
          'job19nut' = 'job19nut',
          'job19wq' = 'job19wq',
          'job20nut' = 'job20nut',
          'job20wq' = 'job20wq',
          'jobjbmet' = 'jobjbmet',
          'kacapmet' = 'kacapmet',
          'kacbcwq' = 'kacbcwq',
          'kacdlwq' = 'kacdlwq',
          'kachdnut' = 'kachdnut',
          'kachdwq' = 'kachdwq',
          'kachhnut' = 'kachhnut',
          'kachomet' = 'kachomet',
          'kachowq' = 'kachowq',
          'kachsnut' = 'kachsnut',
          'kachswq' = 'kachswq',
          'kacpgwq' = 'kacpgwq',
          'kacsdnut' = 'kacsdnut',
          'kacsdwq' = 'kacsdwq',
          'kacsewq' = 'kacsewq',
          'kacssnut' = 'kacssnut',
          'kacsswq' = 'kacsswq',
          'lksbanut' = 'lksbanut',
          'lksblnut' = 'lksblnut',
          'lksolnut' = 'lksolnut',
          'lksponut' = 'lksponut',
          'lkspowq' = 'lkspowq',
          'marabnut' = 'marabnut',
          'marabwq' = 'marabwq',
          'marcemet' = 'marcemet',
          'marcenut' = 'marcenut',
          'marcewq' = 'marcewq',
          'marcwnut' = 'marcwnut',
          'marcwwq' = 'marcwwq',
          'marmbnut' = 'marmbnut',
          'marmbwq' = 'marmbwq',
          'marscnut' = 'marscnut',
          'marscwq' = 'marscwq',
          'narncnut' = 'narncnut',
          'narncwq' = 'narncwq',
          'narpcmet' = 'narpcmet',
          'narpcnut' = 'narpcnut',
          'narpcwq' = 'narpcwq',
          'nartbnut' = 'nartbnut',
          'nartbwq' = 'nartbwq',
          'nartsnut' = 'nartsnut',
          'nartswq' = 'nartswq',
          'nartwnut' = 'nartwnut',
          'nartwwq' = 'nartwwq',
          'niwcawq' = 'niwcawq',
          'niwcbnut' = 'niwcbnut',
          'niwcbwq' = 'niwcbwq',
          'niwdcnut' = 'niwdcnut',
          'niwdcwq' = 'niwdcwq',
          'niwolmet' = 'niwolmet',
          'niwolnut' = 'niwolnut',
          'niwolwq' = 'niwolwq',
          'niwtanut' = 'niwtanut',
          'niwtawq' = 'niwtawq',
          'nocecnut' = 'nocecnut',
          'nocecwq' = 'nocecwq',
          'noclcnut' = 'noclcnut',
          'noclcwq' = 'noclcwq',
          'nocrcmet' = 'nocrcmet',
          'nocrcnut' = 'nocrcnut',
          'nocrcwq' = 'nocrcwq',
          'noczbnut' = 'noczbnut',
          'noczbwq' = 'noczbwq',
          'owcbrnut' = 'owcbrnut',
          'owcbrwq' = 'owcbrwq',
          'owcdrnut' = 'owcdrnut',
          'owcdrwq' = 'owcdrwq',
          'owcolnut' = 'owcolnut',
          'owcolwq' = 'owcolwq',
          'owcowmet' = 'owcowmet',
          'owcsunut' = 'owcsunut',
          'owcsuwq' = 'owcsuwq',
          'owcwmnut' = 'owcwmnut',
          'owcwmwq' = 'owcwmwq',
          'pdbbpnut' = 'pdbbpnut',
          'pdbbpwq' = 'pdbbpwq',
          'pdbbynut' = 'pdbbynut',
          'pdbbywq' = 'pdbbywq',
          'pdbgdnut' = 'pdbgdnut',
          'pdbgsnut' = 'pdbgsnut',
          'pdbgswq' = 'pdbgswq',
          'pdbjenut' = 'pdbjenut',
          'pdbjewq' = 'pdbjewq',
          'pdbjlnut' = 'pdbjlnut',
          'pdbjlwq' = 'pdbjlwq',
          'pdbnnwq' = 'pdbnnwq',
          'pdbpfmet' = 'pdbpfmet',
          'rkbbmwq' = 'rkbbmwq',
          'rkbbrwq' = 'rkbbrwq',
          'rkbfbnut' = 'rkbfbnut',
          'rkbfbwq' = 'rkbfbwq',
          'rkbfunut' = 'rkbfunut',
          'rkbfuwq' = 'rkbfuwq',
          'rkbhcmet' = 'rkbhcmet',
          'rkblhnut' = 'rkblhnut',
          'rkblhwq' = 'rkblhwq',
          'rkbmbnut' = 'rkbmbnut',
          'rkbmbwq' = 'rkbmbwq',
          'rkbpbnut' = 'rkbpbnut',
          'rkbuhmet' = 'rkbuhmet',
          'rkbuhwq' = 'rkbuhwq',
          'sapbcwq' = 'sapbcwq',
          'sapcanut' = 'sapcanut',
          'sapcawq' = 'sapcawq',
          'sapdcnut' = 'sapdcnut',
          'sapdcwq' = 'sapdcwq',
          'sapfdnut' = 'sapfdnut',
          'sapfdwq' = 'sapfdwq',
          'saphdnut' = 'saphdnut',
          'saphdwq' = 'saphdwq',
          'sapldnut' = 'sapldnut',
          'sapldwq' = 'sapldwq',
          'sapmlmet' = 'sapmlmet',
          'sapmlnut' = 'sapmlnut',
          'sapmlwq' = 'sapmlwq',
          'sfbccnut' = 'sfbccnut',
          'sfbccwq' = 'sfbccwq',
          'sfbfmnut' = 'sfbfmnut',
          'sfbfmwq' = 'sfbfmwq',
          'sfbgcnut' = 'sfbgcnut',
          'sfbgcwq' = 'sfbgcwq',
          'sfbrrmet' = 'sfbrrmet',
          'sfbsmnut' = 'sfbsmnut',
          'sfbsmwq' = 'sfbsmwq',
          'sosbhnut' = 'sosbhnut',
          'soschnut' = 'soschnut',
          'soschwq' = 'soschwq',
          'soscmmet' = 'soscmmet',
          'soscsnut' = 'soscsnut',
          'sosecwq' = 'sosecwq',
          'sossewq' = 'sossewq',
          'sosvanut' = 'sosvanut',
          'sosvawq' = 'sosvawq',
          'soswinut' = 'soswinut',
          'soswiwq' = 'soswiwq',
          'tjrbrnut' = 'tjrbrnut',
          'tjrbrwq' = 'tjrbrwq',
          'tjrmmnut' = 'tjrmmnut',
          'tjrmmwq' = 'tjrmmwq',
          'tjrosnut' = 'tjrosnut',
          'tjroswq' = 'tjroswq',
          'tjrpenut' = 'tjrpenut',
          'tjrpewq' = 'tjrpewq',
          'tjrprnut' = 'tjrprnut',
          'tjrprwq' = 'tjrprwq',
          'tjrrcnut' = 'tjrrcnut',
          'tjrrcwq' = 'tjrrcwq',
          'tjrrmnut' = 'tjrrmnut',
          'tjrsbnut' = 'tjrsbnut',
          'tjrsbwq' = 'tjrsbwq',
          'tjrtlmet' = 'tjrtlmet',
          'tjrtlnut' = 'tjrtlnut',
          'tjrtlwq' = 'tjrtlwq',
          'weldnwq' = 'weldnwq',
          'welhtnut' = 'welhtnut',
          'welhtwq' = 'welhtwq',
          'welinnut' = 'welinnut',
          'welinwq' = 'welinwq',
          'wellfmet' = 'wellfmet',
          'wellmnut' = 'wellmnut',
          'wellmwq' = 'wellmwq',
          'welmlnut' = 'welmlnut',
          'welmlwq' = 'welmlwq',
          'welsmnut' = 'welsmnut',
          'welsmwq' = 'welsmwq',
          'welupwq' = 'welupwq',
          'wkbfrnut' = 'wkbfrnut',
          'wkbfrwq' = 'wkbfrwq',
          'wkbmbnut' = 'wkbmbnut',
          'wkbmbwq' = 'wkbmbwq',
          'wkbmrnut' = 'wkbmrnut',
          'wkbmrwq' = 'wkbmrwq',
          'wkbshmet' = 'wkbshmet',
          'wkbwbmet' = 'wkbwbmet',
          'wkbwbnut' = 'wkbwbnut',
          'wkbwbwq' = 'wkbwbwq',
          'wkbwsnut' = 'wkbwsnut',
          'wqbcbwq' = 'wqbcbwq',
          'wqbchmet' = 'wqbchmet',
          'wqbcrnut' = 'wqbcrnut',
          'wqbcrwq' = 'wqbcrwq',
          'wqbctwq' = 'wqbctwq',
          'wqbmhnut' = 'wqbmhnut',
          'wqbmhwq' = 'wqbmhwq',
          'wqbmpnut' = 'wqbmpnut',
          'wqbmpwq' = 'wqbmpwq',
          'wqbnbwq' = 'wqbnbwq',
          'wqbnswq' = 'wqbnswq',
          'wqbslnut' = 'wqbslnut',
          'wqbslwq' = 'wqbslwq'
          ),
        
        selected = "acebbwq")
      
    ),
    
    column(4,
      h3('Select date range'), 
    
      uiOutput("years")
      
    ),
  
    column(4,
      h3('Select variable'), 
    
      uiOutput("parms")
      
    )
    
  ),
  
  fluidRow(
    
    tabsetPanel(
      
      tabPanel('Plot',
        
        # Show the plot,
        plotOutput("outplot", width = "100%"),
        
        tags$style(type="text/css",
            ".shiny-output-error { visibility: hidden; }",
            ".shiny-output-error:before { visibility: hidden; }")
        
      ), 
      
      tabPanel('Monthly summary',
        
        column(12, 
          p('Tabular summary of monthly aggregations showing minimum, first quartile, median, mean, third quartile, maximum, missing values, and variance.'),
          dataTableOutput('outtab_sum_mo')
        )
        
      ), 
      
      tabPanel('Monthly, annual summary',
        
        column(12, 
          p('Average values for monthly aggregations by year.  The trend indicates the average value across all years for the same month and the anomaly is the difference between the mean and trend.'),
          dataTableOutput('outtab_sum_moyr')
          )
          
        ), 
      
      tabPanel('Annual summary',
        
        column(12, 
          p('Average values for annual aggregations.  The anomalies are the differences between the annual averages and overall average.'),
          dataTableOutput('outtab_sum_yr')
          )
        ), 
      
      tabPanel('Downloads',
        
        column(12, 
          p('Click the buttons below to download a pdf of the plots.'),
          column(4, 
            numericInput('height', 'Plot height (in)', value = 8, min = 0, step = 1)
            ),
          column(4, 
            numericInput('width', 'Plot width (in)', value = 13, min = 0, step = 1)
            ),
          column(12, 
            HTML('<p></p>'),
            downloadButton('downloadplot', 'Complete plot'),
            HTML('<p></p>'),
            downloadButton('downloadplot1', 'Monthly means'),
            HTML('<p></p>'),
            downloadButton('downloadplot2', 'Monthly boxplots'),
            HTML('<p></p>'),
            downloadButton('downloadplot3', 'Monthly histograms'),
            HTML('<p></p>'),
            downloadButton('downloadplot4', 'Monthly, annual means'),
            HTML('<p></p>'),
            downloadButton('downloadplot5', 'Monthly, annual anomalies'),
            HTML('<p></p>'),
            downloadButton('downloadplot6', 'Annual anomalies')
            )
          )
          
        )
      
  ))
    
))